""" Variables: Alpha, CoefficientLift, reynoldsNumber, coefficientMoment, CoefficientParasiteDrag
    Training RSquare # = 0.8821392
    Validation RSquare # = 0.8838838
 """

from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ====================================================================
 Copyright (C) 2022 JMP Statistical Discovery LLC. All rights reserved.
 
 Notice: The following permissions are granted provided that the above
 copyright and this notice appear in the score code and any related
 documentation. Permission to copy, modify and distribute the score
 code generated using JMP (r) software is limited to customers of JMP
 Statistical Discovery LLC ("JMP") and successive third parties, all
 without any warranty, express or implied, or any other obligation by
 JMP. JMP and all other JMP Statistical Discovery LLC product and
 service names are registered trademarks or trademarks of JMP
 Statistical Discovery LLC in the USA and other countries. Except as
 contained in this notice, the name of JMP shall not be used in the
 advertising or promotion of products or services without prior
 written authorization from JMP Statistical Discovery LLC.
 ==================================================================== """

""" Python code generated by JMP 17.0.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"topXTR", "table": u"combinedAirfoilDataLabeled", "version": u"17.0.0", "timestamp": u"2025-09-26T04:22:12Z"}


def getInputMetadata():
    return {
        u"alpha": "float",
        u"coefficientLift": "float",
        u"coefficientMoment": "float",
        u"coefficientParasiteDrag": "float",
        u"reynoldsNumber": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted topXTR": "float"
	}


def score(indata, outdata):




    H1_1 = tanh((-0.331038297777097 + -0.0465496961568834 * indata[u"alpha"] + 2.24607453247801 * indata[u"coefficientLift"] + 2.46895272228117 * indata[u"coefficientMoment"] + -3.20947100913513 * indata[u"coefficientParasiteDrag"] + 0.0000006891159770785 * indata[u"reynoldsNumber"]))

    H1_2 = tanh((1.39454938701866 + -0.293906182208142 * indata[u"alpha"] + 2.24934828749425 * indata[u"coefficientLift"] + 10.3624300386215 * indata[u"coefficientMoment"] + 35.7044896758047 * indata[u"coefficientParasiteDrag"] + 0.0000026712426153177 * indata[u"reynoldsNumber"]))

    H1_3 = tanh((1.09495906119778 + -0.0986559352446222 * indata[u"alpha"] + -1.38039488634004 * indata[u"coefficientLift"] + -12.9077635374701 * indata[u"coefficientMoment"] + -0.324414147024637 * indata[u"coefficientParasiteDrag"] + -0.0000004473666111737 * indata[u"reynoldsNumber"]))

    outdata[u"Predicted topXTR"] = 3.35543579040096 + -0.192267204041515 * H1_1 + -2.84957150024152 * H1_2 + 0.281231289685252 * H1_3

    return outdata[u"Predicted topXTR"]



